
import { Job } from '../types';

export const mockJobs: Job[] = [
    {
        id: '101',
        title: 'Lead Barista',
        venueName: 'The Daily Grind',
        location: '123 Coffee Bean Blvd, Brewtown',
        type: 'Full-Time',
        salary: '55000',
        payType: 'salary',
        description: 'Seeking an experienced and passionate barista to lead our morning shift. Must have a love for coffee and great customer service skills. Responsibilities include training new staff, managing inventory, and creating a welcoming atmosphere.',
        roleCategories: ['Barista', 'Manager'],
        status: 'open',
        applicants: [],
        isNew: true,
    },
    {
        id: '102',
        title: 'Head Chef',
        venueName: 'The Gourmet Kitchen',
        location: '456 Culinary Corner, FoodieVille',
        type: 'Full-Time',
        salary: '75000',
        payType: 'salary',
        description: 'An exciting opportunity for a creative and experienced Head Chef. You will be responsible for menu development, kitchen management, and ensuring the highest quality of food production. A passion for seasonal ingredients is a must.',
        roleCategories: ['Chef', 'Kitchen Manager'],
        status: 'open',
        applicants: [],
        isNew: true,
    },
    {
        id: '103',
        title: 'Part-Time Waiter',
        venueName: 'The Seaside Grill',
        location: '789 Ocean View, Beachtown',
        type: 'Part-Time',
        salary: '22',
        payType: 'hourly',
        description: 'Join our friendly team as a part-time waiter. We are looking for someone with a positive attitude and a willingness to learn. Flexible hours available, perfect for students.',
        roleCategories: ['Server'],
        status: 'open',
        applicants: [],
        isNew: false,
    },
    {
        id: '104',
        title: 'Hotel Concierge',
        venueName: 'The Grand Hotel',
        location: '1 Grand Lane, Uptown',
        type: 'Full-Time',
        salary: '60000',
        payType: 'salary',
        description: 'The Grand Hotel is seeking a professional and courteous concierge to be the face of our establishment. You will be responsible for assisting guests with a variety of requests and ensuring a memorable stay.',
        roleCategories: ['Front of House', 'Customer Service'],
        status: 'open',
        applicants: [],
        isNew: false,
    },
];
